#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VERSIONS="${DAIANA_MIGRATION_TEST_PG_VERSIONS:-}"

if [ -z "$VERSIONS" ]; then
  printf 'SKIP: set DAIANA_MIGRATION_TEST_PG_VERSIONS="15 17" to run disposable PostgreSQL migration tests\n'
  exit 0
fi

command -v docker >/dev/null 2>&1 || { printf 'FAIL: docker is required\n' >&2; exit 1; }
docker info >/dev/null 2>&1 || { printf 'FAIL: Docker daemon is unavailable\n' >&2; exit 1; }

log() { printf '===> %s\n' "$*" >&2; }
die() { printf 'ERROR: %s\n' "$*" >&2; return 1; }
docker_cmd() { command docker "$@"; }

cd "$ROOT_DIR"
# shellcheck disable=SC1091
source "$ROOT_DIR/utils/daiana-migrations.sh"

for pg_version in $VERSIONS; do
  case "$pg_version" in 15|17) ;; *) die "Unsupported test PostgreSQL version: $pg_version"; exit 1 ;; esac
  container="daiana-migration-test-pg${pg_version}-$$"
  work_dir="$(mktemp -d)"
  cleanup() {
    docker rm -f "$container" >/dev/null 2>&1 || true
    rm -rf "$work_dir"
  }
  trap cleanup EXIT INT TERM

  docker run --rm -d --name "$container" -e POSTGRES_PASSWORD=test-password "postgres:${pg_version}-alpine" >/dev/null
  ready=0
  for _attempt in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30; do
    if docker exec "$container" pg_isready -U postgres >/dev/null 2>&1; then ready=1; break; fi
    sleep 1
  done
  [ "$ready" -eq 1 ] || die "PostgreSQL $pg_version did not become ready"

  docker exec -i -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -v ON_ERROR_STOP=1 <<'SQL'
CREATE ROLE anon NOLOGIN;
CREATE ROLE authenticated NOLOGIN;
CREATE ROLE service_role NOLOGIN;
CREATE SCHEMA private AUTHORIZATION postgres;
CREATE TABLE public.tenants ("idTenant" integer PRIMARY KEY);
CREATE TABLE public.tenant_plans (
  id integer PRIMARY KEY, "idTenant" integer NOT NULL, "planName" text NOT NULL,
  "maxMessages" integer, "studioIntegrated" boolean, "periodStartAt" timestamptz NOT NULL,
  "expiresAt" timestamptz, "validatedAt" timestamptz, status text NOT NULL,
  "createdAt" timestamptz, "updatedAt" timestamptz
);
CREATE TABLE public.aibot ("idBot" integer PRIMARY KEY, "idTenant" integer NOT NULL, botpublic boolean NOT NULL);
CREATE TABLE public.history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idBot" integer NOT NULL, "idUser" integer, message text NOT NULL,
  created text, metadata jsonb, dataframe jsonb, "createdAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT history_message_not_reject CHECK (message <> 'reject')
);
CREATE SCHEMA studio;
CREATE TABLE studio.organization (id uuid PRIMARY KEY);
CREATE TABLE studio.workspace (id uuid PRIMARY KEY, "organizationId" uuid NOT NULL);
INSERT INTO public.tenants VALUES (1);
INSERT INTO public.tenant_plans VALUES (1, 1, 'studio', 100, true, now(), now() + interval '1 year', now(), 'active', now(), now());
INSERT INTO public.aibot VALUES (10, 1, true), (11, 1, false);
INSERT INTO public.history ("idBot", "idUser", message, created) VALUES
  (10, 1, 'public historical', 'bot'), (11, 1, 'private historical', 'bot');
INSERT INTO studio.organization VALUES ('ca2a7ece-14c6-458c-9266-5c3d96e547f2');
INSERT INTO studio.workspace VALUES ('cd469aed-4042-477b-b508-9de39d395056', 'ca2a7ece-14c6-458c-9266-5c3d96e547f2');
SQL

  export POSTGRES_PASSWORD=test-password POSTGRES_DB=postgres DAIANA_DB_CONTAINER="$container"
  export DAIANA_MIGRATIONS_DIR="$ROOT_DIR/volumes/db/daiana-migrations"
  run_daiana_migrations
  run_daiana_migrations

  docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -v ON_ERROR_STOP=1 \
    -c 'BEGIN; SELECT pg_advisory_xact_lock(1480867157, 1296651378); SELECT pg_sleep(3); COMMIT;' >/dev/null &
  lock_pid=$!
  sleep 1
  lock_start="$(date +%s)"
  run_daiana_migrations
  wait "$lock_pid"
  lock_elapsed=$(( $(date +%s) - lock_start ))
  [ "$lock_elapsed" -ge 2 ] || die "PostgreSQL $pg_version runner did not wait for the global advisory lock"

  result="$(docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -Atqc "
    SELECT count(*) = 1 FROM private.daiana_installer_schema_migrations;
    SELECT public.resolve_daiana_tenant_from_studio('ca2a7ece-14c6-458c-9266-5c3d96e547f2', 'cd469aed-4042-477b-b508-9de39d395056') = 1;
    SELECT NOT has_table_privilege('anon', 'public.tenant_message_quota_periods', 'SELECT');
    SELECT NOT has_table_privilege('service_role', 'public.tenant_message_quota_periods', 'INSERT');
    SELECT has_table_privilege('service_role', 'public.tenant_message_quota_periods', 'SELECT');
    SELECT has_function_privilege('service_role', 'public.reserve_tenant_message_quota(integer,text,text,timestamptz)', 'EXECUTE');
    SELECT NOT has_function_privilege('authenticated', 'public.reserve_tenant_message_quota(integer,text,text,timestamptz)', 'EXECUTE');
    SELECT has_function_privilege('service_role', 'public.finalize_tenant_message_quota_turn(text,text,jsonb,timestamptz)', 'EXECUTE');
    SELECT NOT has_function_privilege('authenticated', 'public.finalize_tenant_message_quota_turn(text,text,jsonb,timestamptz)', 'EXECUTE');
    SELECT proconfig = ARRAY['search_path=pg_catalog, public'] FROM pg_proc WHERE oid = 'public.finalize_tenant_message_quota_turn(text,text,jsonb,timestamptz)'::regprocedure;
    SELECT pg_get_userbyid(proowner) = 'postgres' FROM pg_proc WHERE oid = 'public.finalize_tenant_message_quota_turn(text,text,jsonb,timestamptz)'::regprocedure;")"
  [ "$(printf '%s\n' "$result" | grep -c '^t$')" -eq 11 ] || die "PostgreSQL $pg_version object/RPC/privilege checks failed: $result"

  docker exec -i -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -v ON_ERROR_STOP=1 <<'SQL'
DO $$
DECLARE
  v_result jsonb;
  v_before bigint;
  v_consumed integer;
  v_reserved integer;
BEGIN
  v_result := public.reserve_tenant_message_quota(1, 'released-retry', 'integration');
  IF v_result->>'status' <> 'reserved' OR (v_result->>'consumed')::integer <> 1 THEN
    RAISE EXCEPTION 'public-only bootstrap failed: %', v_result;
  END IF;
  IF public.reserve_tenant_message_quota(1, 'released-retry', 'integration')->>'status' <> 'already_reserved' THEN
    RAISE EXCEPTION 'reserved idempotency failed';
  END IF;
  PERFORM public.release_tenant_message_quota(1, 'released-retry', 'integration');
  v_result := public.reserve_tenant_message_quota(1, 'released-retry', 'integration');
  IF v_result->>'status' <> 'reserved' THEN RAISE EXCEPTION 'released retry was not reactivated: %', v_result; END IF;
  PERFORM public.release_tenant_message_quota(1, 'released-retry', 'integration');

  PERFORM public.reserve_tenant_message_quota(1, 'atomic-success', 'integration');
  SELECT count(*) INTO v_before FROM public.history;
  v_result := public.finalize_tenant_message_quota_turn(
    'atomic-success', 'integration',
    '[{"idBot":10,"idUser":7,"message":"question","created":"user","metadata":{}},{"idBot":10,"idUser":7,"message":"answer","created":"bot","metadata":{}}]'::jsonb
  );
  IF v_result->>'status' <> 'consumed' OR jsonb_array_length(v_result->'history') <> 1 THEN
    RAISE EXCEPTION 'atomic finalize failed: %', v_result;
  END IF;
  SELECT "consumedMessages", "reservedMessages" INTO v_consumed, v_reserved
  FROM public.tenant_message_quota_periods WHERE "idTenant" = 1;
  IF v_consumed <> 2 OR v_reserved <> 0 OR (SELECT count(*) FROM public.history) <> v_before + 2 THEN
    RAISE EXCEPTION 'atomic finalize counters/history mismatch';
  END IF;
  v_result := public.finalize_tenant_message_quota_turn(
    'atomic-success', 'integration',
    '[{"idBot":10,"idUser":7,"message":"question","created":"user"},{"idBot":10,"idUser":7,"message":"answer","created":"bot"}]'::jsonb
  );
  IF v_result->>'status' <> 'already_consumed' OR (SELECT count(*) FROM public.history) <> v_before + 2 THEN
    RAISE EXCEPTION 'finalize idempotency failed: %', v_result;
  END IF;

  PERFORM public.reserve_tenant_message_quota(1, 'expired-finalize', 'integration', now() - interval '20 minutes');
  v_result := public.finalize_tenant_message_quota_turn(
    'expired-finalize', 'integration',
    '[{"idBot":10,"idUser":8,"message":"old question","created":"user"},{"idBot":10,"idUser":8,"message":"old answer","created":"bot"}]'::jsonb
  );
  IF v_result->>'status' <> 'already_released' THEN RAISE EXCEPTION 'expired reservation was not reclaimed: %', v_result; END IF;

  PERFORM public.reserve_tenant_message_quota(1, 'cross-period', 'integration');
  IF public.reserve_tenant_message_quota(1, 'cross-period', 'integration', now() + interval '2 months')->>'status' <> 'request_id_reused' THEN
    RAISE EXCEPTION 'cross-period request ID reuse was accepted';
  END IF;
  PERFORM public.release_tenant_message_quota(1, 'cross-period', 'integration');

  UPDATE public.tenant_plans SET "maxMessages" = 2 WHERE "idTenant" = 1;
  v_result := public.reserve_tenant_message_quota(1, 'released-retry', 'integration');
  IF v_result->>'status' <> 'exhausted' OR (SELECT status FROM public.tenant_message_quota_reservations WHERE "idTenant" = 1 AND source = 'integration' AND "requestId" = 'released-retry') <> 'released' THEN
    RAISE EXCEPTION 'released retry bypassed capacity: %', v_result;
  END IF;
  UPDATE public.tenant_plans SET "maxMessages" = 100 WHERE "idTenant" = 1;

  PERFORM public.reserve_tenant_message_quota(1, 'atomic-rollback', 'integration');
END;
$$;
SQL

  if rollback_error="$(docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -v ON_ERROR_STOP=1 -c "SELECT public.finalize_tenant_message_quota_turn('atomic-rollback', 'integration', '[{\"idBot\":10,\"idUser\":9,\"message\":\"question\",\"created\":\"user\"},{\"idBot\":10,\"idUser\":9,\"message\":\"reject\",\"created\":\"bot\"}]'::jsonb);" 2>&1)"; then
    die "PostgreSQL $pg_version atomic finalize rollback scenario succeeded"
  fi
  [[ "$rollback_error" == *'history_message_not_reject'* ]] || die "PostgreSQL $pg_version finalize failure was unclear"
  rollback_state="$(docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -Atqc "
    SELECT status = 'reserved' FROM public.tenant_message_quota_reservations WHERE \"idTenant\" = 1 AND source = 'integration' AND \"requestId\" = 'atomic-rollback';
    SELECT \"reservedMessages\" = 1 AND \"consumedMessages\" = 2 FROM public.tenant_message_quota_periods WHERE \"idTenant\" = 1;
    SELECT count(*) = 0 FROM public.history WHERE message = 'reject';")"
  [ "$(printf '%s\n' "$rollback_state" | grep -c '^t$')" -eq 3 ] || die "PostgreSQL $pg_version finalize did not roll back atomically: $rollback_state"

  provisioned="$(docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -Atqc "
    SELECT private.provision_known_studio_mapping() = 'provisioned';
    SELECT count(*) = 1 FROM public.tenant_studio_organization_mappings;
    SELECT count(*) = 1 FROM public.tenant_studio_workspace_mappings;")"
  [ "$(printf '%s\n' "$provisioned" | grep -c '^t$')" -eq 3 ] || die "PostgreSQL $pg_version known mapping is not idempotent"

  custom="$(docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -Atqc "BEGIN;
    DELETE FROM public.tenant_studio_workspace_mappings; DELETE FROM public.tenant_studio_organization_mappings;
    DELETE FROM public.tenant_plans; DELETE FROM public.tenants; DELETE FROM studio.workspace; DELETE FROM studio.organization;
    SELECT private.provision_known_studio_mapping() = 'skipped_custom'; ROLLBACK;")"
  [ "$custom" = t ] || die "PostgreSQL $pg_version custom seed-free install did not skip provisioning"

  if partial_error="$(docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -v ON_ERROR_STOP=1 -c "BEGIN; DELETE FROM studio.workspace; SELECT private.provision_known_studio_mapping();" 2>&1)"; then
    die "PostgreSQL $pg_version partial seed set did not fail"
  fi
  [[ "$partial_error" == *'partial expected seed objects'* ]] || die "PostgreSQL $pg_version partial seed failure was unclear"
  if conflict_error="$(docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -v ON_ERROR_STOP=1 -c "BEGIN; INSERT INTO public.tenants VALUES (2); DELETE FROM public.tenant_studio_workspace_mappings; DELETE FROM public.tenant_studio_organization_mappings; INSERT INTO public.tenant_studio_organization_mappings VALUES (2, 'ca2a7ece-14c6-458c-9266-5c3d96e547f2'); SELECT private.provision_known_studio_mapping();" 2>&1)"; then
    die "PostgreSQL $pg_version conflicting known mapping did not fail"
  fi
  [[ "$conflict_error" == *'Conflicting fixed Studio organization mapping'* ]] || die "PostgreSQL $pg_version mapping conflict failure was unclear"

  cp "$ROOT_DIR/volumes/db/daiana-migrations/20260717120000_add_shared_message_quota.sql" "$work_dir/20260717120000_add_shared_message_quota.sql"
  printf '\n-- checksum drift test\n' >> "$work_dir/20260717120000_add_shared_message_quota.sql"
  DAIANA_MIGRATIONS_DIR="$work_dir"
  export DAIANA_MIGRATIONS_DIR
  if run_daiana_migrations; then die "PostgreSQL $pg_version checksum drift was accepted"; fi
  count="$(docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -Atqc 'SELECT count(*) FROM private.daiana_installer_schema_migrations;')"
  [ "$count" = 1 ] || die "PostgreSQL $pg_version drift changed history"

  rm -f "$work_dir/20260717120000_add_shared_message_quota.sql"
  printf 'CREATE TABLE public.must_rollback(id integer);\nSELECT 1/0;\n' > "$work_dir/20260717130000_failure.sql"
  if run_daiana_migrations; then die "PostgreSQL $pg_version failing migration succeeded"; fi
  recorded="$(docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -Atqc "SELECT count(*) FROM private.daiana_installer_schema_migrations WHERE version = '20260717130000';")"
  table_exists="$(docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -Atqc "SELECT to_regclass('public.must_rollback') IS NOT NULL;")"
  [ "$recorded" = 0 ] && [ "$table_exists" = f ] || die "PostgreSQL $pg_version failed migration was not atomic"

  printf 'PASS: PostgreSQL %s apply/replay/drift/failure/quota/finalize/privilege/RPC checks\n' "$pg_version"
  cleanup
  trap - EXIT INT TERM
done
